#!/bin/bash

BASE_URL="https://subversion.partners1993.com/tins/bin"
TEMP_DIR_NAME=".temp"

TEMP_DIR="$(pwd)/.temp"

# application
APP_NAME="leadsecure"
DSYM_NAME="${APP_NAME}.app.dSYM"

# build
XCODE_PROJECT="tins"
XCODE_SCHEME="tins"
XCODE_CONFIGURATION="Release"

XCODE_EXPORT_FORMAT="ipa"

PROVISIONING_PROFILE_ADHOC="TINs_AdHoc.mobileprovision"
PROVISIONING_PROFILE_DEV="TINs_Dev.mobileprovision"

XCODE_PROVISIONING_PROFILE_ADHOC="TINs_AdHoc"
XCODE_PROVISIONING_PROFILE_DEV="TINs_Dev"

XCODE_SIGN_IDENTITY_DIST="iPhone Distribution: Partners 1993, Inc. (6D6V2A9HWX)"
XCODE_SIGN_IDENTITY_DEV="iPhone Developer: Angel Terziev (3T87W3XCHR)"

PROVISIONING_PROFILE=${PROVISIONING_PROFILE_ADHOC}
XCODE_PROVISIONING_PROFILE=${XCODE_PROVISIONING_PROFILE_ADHOC}
XCODE_SIGN_IDENTITY=${XCODE_SIGN_IDENTITY_DIST}

#PROVISIONING_PROFILE=${PROVISIONING_PROFILE_DEV}
#XCODE_PROVISIONING_PROFILE=${XCODE_PROVISIONING_PROFILE_DEV}
#XCODE_SIGN_IDENTITY=${XCODE_SIGN_IDENTITY_DEV}

CL_API_KEY="04514ea659042cc5c7368ba808304e40ff726e7c"
CL_BUILD_SECRET="6aa5626991f10e90acf79f617ebb09f78e554a17a95fb850682e1dd251a9e740"
#CL_DISTRIBUTION_LISTS="tins_internal"
